# data_models.py
from typing import List, Optional, Literal, Dict, Any, Union
from pydantic import BaseModel, Field, model_validator


# Define the Absolute CAT Taxonomy

# --- SUBJECT: QUANTITATIVE APTITUDE ---
Quant_Topics = Literal[
    "Arithmetic", "Algebra", "Geometry & Mensuration", 
    "Number System", "Modern Math"
]
Quant_SubTopics = Literal[
    # Arithmetic
    "Percentages", "Profit, Loss & Discount", "Simple & Compound Interest",
    "Ratio, Proportion & Variation", "Averages", "Mixtures & Alligations",
    "Time & Work", "Time, Speed & Distance",
    # Algebra
    "Linear Equations", "Quadratic Equations", "Higher Degree Polynomials",
    "Inequalities", "Logarithms", "Functions & Graphs", "Maxima & Minima",
    # Geometry & Mensuration
    "Lines & Angles", "Triangles", "Circles", "Quadrilaterals & Polygons",
    "Coordinate Geometry", "Mensuration (2D & 3D)", "Trigonometry",
    # Number System
    "Factors & Multiples (LCM/HCF)", "Remainders & Divisibility",
    "Base Systems", "Digits & Properties", 
    # Modern Math
    "Permutations & Combinations", "Probability", 
    "Sequence & Series (AP/GP/HP)", "Set Theory",
    # Escape Hatch
    "Miscellaneous Quant"
]


# --- SUBJECT: DATA INTERPRETATION & LOGICAL REASONING ---
DILR_Topics = Literal[
    "Data Interpretation", "Logical Reasoning", "DI-LR Hybrid"
]
DILR_SubTopics = Literal[
    # Data Interpretation
    "Data Tables", "Bar Graphs", "Line Charts", "Pie Charts", 
    "Scatter Plots & Bubble Charts", "Radar/Spider Web Charts", 
    "Caselets (Paragraph DI)", "Missing Data DI",
    # Logical Reasoning
    "Linear Arrangement", "Circular/Polygon Arrangement",
    "Matrix & Grid Puzzles", "Blood Relations", "Direction Sense",
    "Syllogisms & Logic Gates", "Cubes & Dices", "Cryptarithmetic",
    # Advanced / Hybrid
    "Games & Tournaments", "Routes & Networks", "Scheduling", 
    "Optimization & Max/Min", "Venn Diagrams (Multi-set)",
    # Escape Hatch
    "Miscellaneous DILR"
]


# --- SUBJECT: VERBAL ABILITY & READING COMPREHENSION ---
VARC_Topics = Literal[
    "Reading Comprehension", "Verbal Ability"
]
VARC_SubTopics = Literal[
    # Reading Comprehension (Question Types)
    "Main Idea / Central Theme", "Specific Detail / Fact Based",
    "Inference / Implication", "Tone / Attitude of Author",
    "Structure / Organization", "Application of Idea", 
    "Philosophy & Humanities",
    "Psychology & Sociology",
    "Science & Technology",
    "History & Political Science",
    "Ecology & Environment",
    "Business & Economics",
    "Art, Literature & Culture",
    "Zoology & Biology",
    "Miscellaneous RC",
    # Verbal Ability
    "Para Jumbles (TITA)", "Para Jumbles (MCQ)",
    "Odd Sentence Out", "Para Summary", "Para Completion",
    "Grammar & Usage", "Vocabulary & Context",
    # Escape Hatch
    "Miscellaneous VA"
]

# Combine them for the master model
All_Topics = Union[Quant_Topics, DILR_Topics, VARC_Topics]
All_SubTopics = Union[Quant_SubTopics, DILR_SubTopics, VARC_SubTopics]

class OriginalSource(BaseModel):
    label: str
    link: str

class ParentContext(BaseModel):
    context_id: Optional[str] = None
    context_type: Literal["passage", "caselet_text", "table", "chart"]
    context_body: str
    context_images: List[str] = Field(default_factory=list)

class Options(BaseModel):
    A: str
    B: str
    C: str
    D: str

class MetadataHooks(BaseModel):
    trap_type: str = Field(description="The underlying structural pitfall (e.g., double-counting).")
    difficulty: Optional[Literal["Easy", "Medium", "Hard"]] = Field(default="Medium")
    difficulty_level: float = Field(ge=1.0, le=10.0, description="Numeric difficulty from 1.0 to 10.0.")
    calculation_intensity: Literal["Low", "Medium", "High"]
    
    @model_validator(mode='after')
    def calculate_deterministic_difficulty(self):
        if self.difficulty_level < 4.0:
            self.difficulty = "Easy"
        elif self.difficulty_level >= 7.0:
            self.difficulty = "Hard"
        else:
            self.difficulty = "Medium"
        return self

class CATUnifiedQuestion(BaseModel):
    id: str
    subject: Literal["Quant", "DILR", "VARC"]
    question_type: Optional[Literal["MCQ", "TITA"]] = Field(default="MCQ")
    topic: All_Topics
    sub_topic: All_SubTopics
    
    # Text and Structure (Copied exactly from source)
    question_text: str
    question_images: List[str] = Field(default_factory=list)
    options: Optional[Options] = None
    correct_answer: Optional[str]
    solution_text: Optional[str] = None
    solution_images: List[str] = Field(default_factory=list)
    original_sources: List[OriginalSource] = Field(default_factory=list)
    
    # Metadata generated by AI
    metadata_hooks: MetadataHooks
    semantic_keywords: List[str] = Field(description="Extract 3-5 core mathematical/logical concepts.")
    has_parent_context: bool = Field(default=False)
    parent_context: Optional[ParentContext] = None

    @model_validator(mode='after')
    def calculate_question_type(self):
        if self.options is not None:
            self.question_type = "MCQ"
        else:
            self.question_type = "TITA"
        return self

class CATExtractionBatch(BaseModel):
    batch_type: Literal["STANDALONE", "SET"]
    parent_context: Optional[ParentContext] = None
    questions: List[CATUnifiedQuestion]


# 2. Enforce it in the LLM Payload
class LLMQuestionMetadata(BaseModel):
    subject: Literal["Quant", "DILR", "VARC"]
    
    # The LLM is now FORCED to pick exactly one of these strings. No drift is possible.
    topic: All_Topics 
    sub_topic: All_SubTopics 
    
    metadata_hooks: MetadataHooks
    
    # We leave this as an open string so the LLM can capture nuanced variations
    semantic_keywords: List[str] = Field(
        description="Extract 3-5 specific keywords from the problem (e.g., 'Trains', 'Relative Speed', 'Upstream')."
    )

class LLMBatchEnrichment(BaseModel):
    question_metadata_list: List[LLMQuestionMetadata] = Field(
        description="An array of metadata objects. MUST match the exact order and length of the provided JSON questions array."
    )

class TestGenerationRequest(BaseModel):
    subject: Optional[str] = None       
    difficulty: Optional[str] = None    
    topic: Optional[str] = None         
    sub_topic: Optional[str] = None     # Granular filtering
    limit: int = 5                      
    
    # Time configuration for the test session
    time_limit_minutes: Optional[int] = None # For full-test timers (e.g., 40 mins)
    time_per_question_seconds: Optional[int] = None # For time-boxed drill modes (e.g., 120s hard stop)

    sort_by_difficulty: bool = False # Default to exam-style shuffling