# data_models.py
from typing import List, Optional, Literal, Dict, Any
from pydantic import BaseModel, Field, model_validator

class OriginalSource(BaseModel):
    label: str
    link: str

class ParentContext(BaseModel):
    context_id: Optional[str] = None
    context_type: Literal["passage", "caselet_text", "table", "chart"]
    context_body: str
    context_images: List[str] = Field(default_factory=list)

class Options(BaseModel):
    A: str
    B: str
    C: str
    D: str

class MetadataHooks(BaseModel):
    trap_type: str = Field(description="The underlying structural pitfall (e.g., double-counting).")
    difficulty: Optional[Literal["Easy", "Medium", "Hard"]] = Field(default="Medium")
    difficulty_level: float = Field(ge=1.0, le=10.0, description="Numeric difficulty from 1.0 to 10.0.")
    calculation_intensity: Literal["Low", "Medium", "High"]
    
    @model_validator(mode='after')
    def calculate_deterministic_difficulty(self):
        if self.difficulty_level < 4.0:
            self.difficulty = "Easy"
        elif self.difficulty_level >= 7.0:
            self.difficulty = "Hard"
        else:
            self.difficulty = "Medium"
        return self

class CATUnifiedQuestion(BaseModel):
    id: str
    subject: Literal["Quant", "DILR", "VARC"]
    question_type: Optional[Literal["MCQ", "TITA"]] = Field(default="MCQ")
    topic: str = Field(description="Generate the high-level topic (e.g., Arithmetic, Logical Reasoning)")
    sub_topic: str = Field(description="Generate the specific sub-topic")
    
    # Text and Structure (Copied exactly from source)
    question_text: str
    question_images: List[str] = Field(default_factory=list)
    options: Optional[Options] = None
    correct_answer: Optional[str]
    solution_text: Optional[str] = None
    solution_images: List[str] = Field(default_factory=list)
    original_sources: List[OriginalSource] = Field(default_factory=list)
    
    # Metadata generated by AI
    metadata_hooks: MetadataHooks
    semantic_keywords: List[str] = Field(description="Extract 3-5 core mathematical/logical concepts.")

    @model_validator(mode='after')
    def calculate_question_type(self):
        if self.options is not None:
            self.question_type = "MCQ"
        else:
            self.question_type = "TITA"
        return self

class CATExtractionBatch(BaseModel):
    batch_type: Literal["STANDALONE", "SET"]
    parent_context: Optional[ParentContext] = None
    questions: List[CATUnifiedQuestion]